CANONICAL_STATES = [
    "Andaman And Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra And Nagar Haveli And Daman And Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
]
CANONICAL_DISTRICTS = [
    "North 24 Parganas",
    "South 24 Parganas",
    "Kolkata",
    "Howrah",
    "Hooghly",
    "Bengaluru Urban",
    "Bengaluru Rural",
    "Mumbai",
    "Pune",
    "Ahmedabad",
    "Surat",
    "Jaipur",
    "Jodhpur",
    "Chennai",
    "Coimbatore",
    "Hyderabad",
    "Warangal",
    "Delhi",
    "New Delhi"
]

